### ISSUE TITLE
LoadError: cannot load such file -- dxopal

### ISSUE THREAD

**Issue by yhara** [yhara/dxopal#19]
I tried releasing v1.4.0 but actually it raises this error:

```
ERROR: LoadError
LoadError: cannot load such file -- dxopal
at Object.Opal.load (http://localhost:7521/dxopal.min.js:1:34889)
at Function.Opal.require (http://localhost:7521/dxopal.min.js:1:35120)
at eval (eval at <anonymous> (http://localhost:7521/dxopal.min.js:1:2171179), <anonymous>:10:8)
at eval (eval at <anonymous> (http://localhost:7521/dxopal.min.js:1:2171179), <anonymous>:22:3)
at http://localhost:7521/dxopal.min.js:1:2171179
at Function.$Kernel_eval$1 (http://localhost:7521/dxopal.min.js:1:2171190)
at Function.$$require_remote (http://localhost:7521/dxopal.min.js:1:2204025)
at $$1 (eval at <anonymous> (http://localhost:7521/dxopal.min.js:1:2171179), <anonymous>:8:15)
at Object.Opal.yieldX (http://localhost:7521/dxopal.min.js:1:22606)
at Function.$$call (http://localhost:7521/dxopal.min.js:1:375302)
```

**Comment by yhara** [comment]
When you use DXOpal as a library, you need `require "dxopal"`. But when you use DXOpal via dxopal.js, you don't need it because DXOpal is already loaded.
